"""add test field

Revision ID: 3efcaef58a7e
Revises: ead267556557
Create Date: 2021-09-01 16:14:54.988719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efcaef58a7e'
down_revision = 'ead267556557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_release', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_release', 'test')
    # ### end Alembic commands ###
