"""new field

Revision ID: 453970b16317
Revises: 6c659fbe10d6
Create Date: 2021-09-01 16:35:09.214031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453970b16317'
down_revision = '6c659fbe10d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_release', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_release', 'test')
    # ### end Alembic commands ###
